services:

  webserver:
    # Aby pliki byly poprawnie synchronizowane między kontenerem a windowsem
    volumes:
      - ./:/var/www/html/
      - vendors:/var/www/html/vendor
      - build:/var/www/html/public/build
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - initializer

  initializer:
    container_name: recruitment-initializer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - build:/var/www/html/public/build
    entrypoint: /bin/sh -c "cp -r /var/www/html/public/build/* /var/www/html/public/build/ || true"
    command: []
    restart: "no"

volumes:
  vendors:
  build: