#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

index:
    path: /{wildcard}
    controller: App\Controller\DefaultController::index
    requirements:
        wildcard: .*


